export const INITIAL_EYE_SEP = 0.5;
export const INITIAL_STEREO_WIDTH = 640;
export const INITIAL_STEREO_HEIGHT = 640;
export const INITIAL_HIGHLIGHT_COLOR = 0xff0000;
export const VIEWER_SCALING_FACTOR = 1.0;